/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define ADD 0
#define SUB 1
#define MUL 2
#define DIV 3

struct CALCULATOR {
	int op;
	float arg1;
	float arg2;
	float result;
};
typedef struct CALCULATOR CALCULATOR;
#ifdef __cplusplus
extern "C" bool_t xdr_CALCULATOR(XDR *, CALCULATOR*);
#elif __STDC__
extern  bool_t xdr_CALCULATOR(XDR *, CALCULATOR*);
#else /* Old Style C */
bool_t xdr_CALCULATOR();
#endif /* Old Style C */


#define CALCULATOR_PROG ((rpc_uint)0x20000001)
#define CALCULATOR_VER ((rpc_uint)1)

#ifdef __cplusplus
#define CALCULATOR_PROC ((rpc_uint)1)
extern "C" struct CALCULATOR * calculator_proc_1(struct CALCULATOR *, CLIENT *);
extern "C" struct CALCULATOR * calculator_proc_1_svc(struct CALCULATOR *, struct svc_req *);

#elif __STDC__
#define CALCULATOR_PROC ((rpc_uint)1)
extern  struct CALCULATOR * calculator_proc_1(struct CALCULATOR *, CLIENT *);
extern  struct CALCULATOR * calculator_proc_1_svc(struct CALCULATOR *, struct svc_req *);

#else /* Old Style C */
#define CALCULATOR_PROC ((rpc_uint)1)
extern  struct CALCULATOR * calculator_proc_1();
extern  struct CALCULATOR * calculator_proc_1_svc();
#endif /* Old Style C */

#endif /* !_CALCULATOR_H_RPCGEN */
