/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)

// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface {
	ChangePostPerms(http.ResponseWriter, *http.Request)
	Comment(http.ResponseWriter, *http.Request)
	DeletePost(http.ResponseWriter, *http.Request)
	DeleteUser(http.ResponseWriter, *http.Request)
	GetPost(http.ResponseWriter, *http.Request)
	Login(http.ResponseWriter, *http.Request)
	Publish(http.ResponseWriter, *http.Request)
	React(http.ResponseWriter, *http.Request)
	Register(http.ResponseWriter, *http.Request)
	Subscribe(http.ResponseWriter, *http.Request)
	Uncomment(http.ResponseWriter, *http.Request)
	UserInfo(http.ResponseWriter, *http.Request)
	ViewComments(http.ResponseWriter, *http.Request)
	ViewFeed(http.ResponseWriter, *http.Request)
	ViewProfilePosts(http.ResponseWriter, *http.Request)
	ViewProfileUser(http.ResponseWriter, *http.Request)
	ViewUsers(http.ResponseWriter, *http.Request)
}

// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultApiServicer interface {
	ChangePostPerms(context.Context, string) (ImplResponse, error)
	Comment(context.Context, string, CommentRequest) (ImplResponse, error)
	DeletePost(context.Context, string) (ImplResponse, error)
	DeleteUser(context.Context, string) (ImplResponse, error)
	GetPost(context.Context, string) (ImplResponse, error)
	Login(context.Context, LoginRequest) (ImplResponse, error)
	Publish(context.Context, PublishRequest) (ImplResponse, error)
	React(context.Context, string, ReactRequest) (ImplResponse, error)
	Register(context.Context, RegisterRequest) (ImplResponse, error)
	Subscribe(context.Context, string) (ImplResponse, error)
	Uncomment(context.Context, string, UncommentRequest) (ImplResponse, error)
	UserInfo(context.Context) (ImplResponse, error)
	ViewComments(context.Context, string) (ImplResponse, error)
	ViewFeed(context.Context) (ImplResponse, error)
	ViewProfilePosts(context.Context, string) (ImplResponse, error)
	ViewProfileUser(context.Context, string) (ImplResponse, error)
	ViewUsers(context.Context) (ImplResponse, error)
}
