/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UncommentRequest struct {
	CommID string `json:"commID"`
}

// AssertUncommentRequestRequired checks if the required fields are not zero-ed
func AssertUncommentRequestRequired(obj UncommentRequest) error {
	elements := map[string]interface{}{
		"commID": obj.CommID,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseUncommentRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UncommentRequest (e.g. [][]UncommentRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUncommentRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUncommentRequest, ok := obj.(UncommentRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUncommentRequestRequired(aUncommentRequest)
	})
}
