/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeleteUserResponse struct {
	Deleted bool `json:"deleted"`
}

// AssertDeleteUserResponseRequired checks if the required fields are not zero-ed
func AssertDeleteUserResponseRequired(obj DeleteUserResponse) error {
	elements := map[string]interface{}{
		"deleted": obj.Deleted,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseDeleteUserResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DeleteUserResponse (e.g. [][]DeleteUserResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDeleteUserResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDeleteUserResponse, ok := obj.(DeleteUserResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDeleteUserResponseRequired(aDeleteUserResponse)
	})
}
