/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ViewProfilePostsResponse struct {
	Posts []Post `json:"posts"`
}

// AssertViewProfilePostsResponseRequired checks if the required fields are not zero-ed
func AssertViewProfilePostsResponseRequired(obj ViewProfilePostsResponse) error {
	elements := map[string]interface{}{
		"posts": obj.Posts,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Posts {
		if err := AssertPostRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseViewProfilePostsResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ViewProfilePostsResponse (e.g. [][]ViewProfilePostsResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseViewProfilePostsResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aViewProfilePostsResponse, ok := obj.(ViewProfilePostsResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertViewProfilePostsResponseRequired(aViewProfilePostsResponse)
	})
}
