/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UncommentResponse struct {
	Uncommented bool `json:"uncommented"`
}

// AssertUncommentResponseRequired checks if the required fields are not zero-ed
func AssertUncommentResponseRequired(obj UncommentResponse) error {
	elements := map[string]interface{}{
		"uncommented": obj.Uncommented,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseUncommentResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UncommentResponse (e.g. [][]UncommentResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUncommentResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUncommentResponse, ok := obj.(UncommentResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUncommentResponseRequired(aUncommentResponse)
	})
}
