/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ChangePermsResponse struct {
	Changed string `json:"changed"`
}

// AssertChangePermsResponseRequired checks if the required fields are not zero-ed
func AssertChangePermsResponseRequired(obj ChangePermsResponse) error {
	elements := map[string]interface{}{
		"changed": obj.Changed,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseChangePermsResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ChangePermsResponse (e.g. [][]ChangePermsResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseChangePermsResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aChangePermsResponse, ok := obj.(ChangePermsResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertChangePermsResponseRequired(aChangePermsResponse)
	})
}
